logo: "/images/Chris-Professional-Web_sm.png?raw=true"
title: Christopher Grace
description: > 
  Data Analyst <br>
  Senior Mechanical Engineer
  <br><br>
  <a href="https://www.linkedin.com/in/cgrace2">View LinkedIn Profile</a> 

theme: jekyll-theme-minimal

# Google Analytics
google_analytics: UA-194794276-1

